
backend:
  name: github
  repo: ALFASHOOTER1/woordshare
  branch: main
  auth_type: implicit
  app_id: Ov23liCGJl8mYHNlk4AD

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "software"
    label: "البرامج"
    folder: "content/software"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "رابط التحميل", name: "download_url", widget: "string" }
      - { label: "الإصدار", name: "version", widget: "string" }
      - { label: "الوصف", name: "body", widget: "markdown" }
